# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            'Matthew Maenner'
tagline:         
description:      ''
url:              http://mjmaenner.github.io
baseurl:          /

author:
  name:           'Matt'
  url:            http://mjmaenner.github.io

paginate:         5

# Custom vars


github:           http://github.com/mjmaenner

theme: jekyll-theme-tactile