# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Matthew Maenner'
tagline:         
description:      'Epidemiologist'
url:              http://mjmaenner.github.io
baseurl:          /

author:
  name:           'Matt'
  url:            http://mjmaenner.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:           http://github.com/mjmaenner
